### ISSUE TITLE
Query: Check for empty String in return value from Server

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix-svelte-front-end#234]
Some queries return an empty String instead of a valid JSON response for the queries (updating queries and store functions for instance).

**Comment by mosheduminer** [comment]
Is there currently an error, or is this an enhancement proposal?
Assuming that it is an enhancement, how would you propose handling such cases?

I am considering adding notifications similar to pgAdmin (fly in from the right, to the bottom right corner, then leave the way it came), for various operations. Perhaps we can show query success/error with such notifications.

**Comment by mosheduminer** [comment]
Resolved by https://github.com/sirixdb/sirix/pull/332
