### ISSUE TITLE
Creating database => SVG width/height NaN error

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix-svelte-front-end#4]
I'm getting this error in the Chrome Console after adding a JSON database.

![Screenshot from 2020-02-17 22-50-36](https://user-images.githubusercontent.com/1202851/74688569-3314ac00-51d8-11ea-80aa-c78934a159cd.png)

**Comment by mosheduminer** [comment]
It's strange that this error shows up, because the width/length attributes are working as expected, regardless of the error. In any case, I switched from using attributes to CSS inline styles. Same effect, no error.
